triggers:
  - agent_command: csat
  - event_type: meya.twilio.flex.event.reservation_completed

steps:
  - status: (@ flow.event.data.worker_attributes.full_name ) has left the chat.
  - say: How did you enjoy your experience?
    quick_replies:
      - text: 👍
        result: good
      - text: 👎
        result: bad
  - say: Thank you for your rating.
