triggers:
  - keyword: start_flex_flow

steps:
  - jump: en

  - (pt)
  - (pt-BR)
  - flow: flow.twilio.flex.portuguese
    transfer: true

  - (en)
  - (en-US)
  - flow: flow.twilio.flex.english
    transfer: true
