id: flow.twilio.flex.reservation_accepted
triggers:
  - event_type: meya.twilio.flex.event.reservation_accepted

steps:
  - status: (@ flow.event.data.agent_name ) has joined the chat.
---
id: flow.twilio.flex.task_queue_entered
triggers:
  - event_type: meya.twilio.flex.event.task_queue_entered

steps:
  - if: (@ flow.event.data.task_priority == "0")
    then:
      status: You're next in line! An agent will be with your shortly.
    else:
      status: You're in the queue. An agent will be with you shortly.
---
id: flow.twilio.flex.task_canceled
triggers:
  - event_type: meya.twilio.flex.event.task_canceled

steps:
  - status: Unfortunately, no agent is available at the moment. Please try again later.
